### PR TITLE
API changes

### PR DESCRIPTION
**Pull request by jacquemier**
API entirely changed
No more access to C librarie thanks pyhessio
A HessioFile class has been created and MUST be used throw pyhessio.open context manager
With the context manager we ensure:
 that only ONE file is open at time.
 that each opened file is correctly closed even if case of Exception.

### CODE REVIEW

**Comment by jacquemier** [comment]
This 1.0.0 version is no more compatible with ctapipe.
ctapipe.io.hessio must now used pyhessio.open context manager function

**Comment by jacquemier** [comment]
This change should resolve iusses:
https://github.com/cta-observatory/pyhessio/issues/37
https://github.com/cta-observatory/pyhessio/issues/38

**Comment by jacquemier** [comment]
This 1.0.0 version is no more compatible with ctapipe.
ctapipe.io.hessio must now used pyhessio.open context manager function

ctapipe Travis test uses pyhessio archive (https://github.com/cta-observatory/pyhessio/archive/v0.5.5.tar.gz). So once this PR accepted, I will create a new pyhessio archive. And ctapipe travis file will have to be modified to used this new pyhessio archive

**Comment by kosack** [comment]
this looks good to me, and it doesn't seem to be too difficult to update `ctapipe` to use the new API (I'm already in the process of completely changing the hessio_event_source and associated Container classes, so it's easy to make this work).

**Comment by jacquemier** [comment]
Ok, so I will  merge this PR, and create a pyhessio archive v1.0.0 now
Please change pyhessio archive in .travis when changing hessio_event_source.

**Pull request merged**
