### PR TITLE
Updated hessio libs to work with new simtel versions

### PR DESCRIPTION
**Pull request by thomasarmstrong**
Encountered problem reading new sim_telarray files with ctapipe that were produced with most recent version of corsika_simtelarray. 
Received errors such as: 

`Unsupported camera definition version: 5.`

and noticed that, for example, the number of recorded pixels was 0.

This was fixed by copying over the hessioxxx/include/ and hessioxxx/lib/ files from the 2018-10-22 version of corsika_simtelarray. I have checked that it is still compatible with older data sets.

### CODE REVIEW

**Comment by jacquemier** [comment]
The return value get_adc_known(38,0,1000) is now to 3 (it was originaly 1).
Because you do not changed pyhessio code but only update the hessio library and get_adc_known is nt used if ctapipe, I think you can change the expected value to 3 in the unittest file.

Please, do not forget to increment  package version value in pyhessio/meta.yaml file.

**Comment by thomasarmstrong** [comment]
For some reason I this has caused issues with move_to_next_mc_event, I am having a look why that might be.

**Comment by thomasarmstrong** [comment]
Ah never mind, just realised that this has been collapsed into move_to_next_event!

**Comment by jacquemier** [comment]
Just before I merge this PL we need to test ctapipe with this version.
@thomasarmstrong , did you already execute ctapipe units test with this pyhessio commit ?

**Comment by thomasarmstrong** [comment]
Sorry I forgot to follow this up, just ran pytest and it seems that there are no obvious problems.

**Pull request merged**
