### PR TITLE
Add some getters

### PR DESCRIPTION
**Pull request by elehcim**
Hello!
I'm dealing with ASTRI data and I found very useful this wrapper which I'm using to convert Montecarlo Data to FITS DL0 used by ASTRI prototype (and the foreseen mini-array). I had to introduce other getters. I hope they could be useful for others.

I added:
* `get_focal_length`
* `get_telescope_position`
* `get_mc_shower_primary_id`
* `get_mc_shower_h_first_int`

### CODE REVIEW

**Comment by jacquemier** [comment]
elehcim,please provide unit tests in pyhessio/tests/test_hessio.py for your new getters.

**Comment by elehcim** [comment]
ok

**Comment by jacquemier** [comment]
And thank you for your participation.

**Comment by elehcim** [comment]
I'm not very familiar with hessio... How do I read the file `gamma_20deg_0deg_run31964___cta-prod2_desert-1640m-Aar.simtel` which is used for the unit tests?

I mean, how to retrieve independently the data which I need to compare with the output from the getters?
I tried using the binary `read_hess` compiled in the old pyhessioxxx repo, but I don't know how to select a single event.

For my tests I used a custom file and I read the ROOT format (actually FITS converted from ROOT).
Thanks!

**Comment by jacquemier** [comment]
1/ I use pytest for unit test, you can have a look here:
http://pytest.org/latest/example/index.html

2/ Data file gamma_20deg_0deg_run31964___cta-prod2_desert-1640m-Aar.simtel can be found here with default CTA password.
http://muon.gae.ucm.es/cta

3/ how to retrieve independently the data which I need to compare with the output from the getters ?
I first run pytest with a wrong value as result of getter in an assert statement.
pytest shows me the correct value in an error message.
Then I use this correct value in my assert statement.

Cheers, Jean

**Comment by kosack** [comment]
there is also a small (10MB) simtelarray file that can be used for testing included in the ctapipe-extra repository (that is automatically checked out with ctapipe). That's easier than with a huge  multi GB data file, probably.

**Comment by jacquemier** [comment]
I created a pyhessio-extra submodule. It contains a datasets folder with same simtelarray file than ctapipe.
Now unit tests used it.

**Pull request merged**
